version: "3.2"
services:
    rabbitmq-server:
        build: ./rabbitmq-server
        tty: true

    python-service:
        build: ./python-service
        depends_on:
          - rabbitmq-server
        tty: true
        ports:
            - "3000:3000"
        volumes:
          - './python-service:/pythonservice'

    go-service:
        build: ./go-service
        depends_on:
          - rabbitmq-server
        tty: true
        volumes:
          - './go-service:/goservice'

volumes:
  python-service:
  go-service: