version: "3.2"
services:
    rabbitmq-server:
        build: ./rabbitmq-server

    python-service:
        build: ./python-service
        # 'rabbitmq-server' will be available as a network reference inside this service.
        depends_on:
          - rabbitmq-server
        tty: true
        ports:
            - "3000:3000"
        volumes:
          - './python-service:/python-service'

    go-service:
        build: ./go-service
        # 'rabbitmq-server' will be available as a network reference inside this service.
        depends_on:
          - rabbitmq-server
        tty: true
        volumes:
          - './go-service:/go-service'

volumes:
    python-service:
    go-service:
